package model;

import java.io.Serializable;
import java.util.Enumeration;
import java.util.ResourceBundle;

import javax.swing.JTree;
import javax.swing.tree.TreeNode;



/**
 * Klasa koja predstavlja jedan cvor {@link JTree} stabla aplikacije
 * 
 * @author Snezana Stevanovic 
 *
 */

@SuppressWarnings("serial")
public class Node implements TreeNode, Serializable {
	
	private String code;
	private String type;
	private String name;
	private Nodes children;
	private Columns columns;
	private Node parent; 
	/**
	 * Kljuc za lokalni naziv cvora u resourceBundle-u
	 */
	private String localNameKey;
	
	public Node(){
		code = "";
		type = "";
		name = "";
		children = new Nodes();
		columns = new Columns();
		parent = null;
	}
	
/** GET AND SET METHODS **/	
	public String getCode() {
		return code;
	}

	

	/**
 * @return the children
 */
public Nodes getChildren() {
	return children;
}

/**
 * @param children the children to set
 */
public void setChildren(Nodes children) {
	this.children = children;
}

	public void setCode(String code) {
		this.code = code;
	}

	

	/**
	 * @return the localNameKey
	 */
	public String getLocalNameKey() {
		return localNameKey;
	}
	
	

	/**
	 * @param localNameKey the localNameKey to set
	 */
	public void setLocalNameKey(String localNameKey) {
		this.localNameKey = localNameKey;
	}

	public String getType() {
		return type;
	}

	public String toString() {
		return name;
	}

	public void setType(String type) {
		this.type = type;
	}



	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public Columns getColumns() {
		return columns;
	}



	public void setColumns(Columns columns) {
		this.columns = columns;
	}



	public void setParent(Node parent) {
		this.parent = parent;
	}


	/** AUTOGENERATED **/
	@Override
	public Enumeration children() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean getAllowsChildren() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public TreeNode getChildAt(int arg0) {
		// TODO Auto-generated method stub
		return children.getChildren(arg0);
	}

	@Override
	public int getChildCount() {
		// TODO Auto-generated method stub
		return children.getChildCount();
	}

	@Override
	public int getIndex(TreeNode arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public TreeNode getParent() {
		// TODO Auto-generated method stub
		return parent;
	}

	@Override
	public boolean isLeaf() {
		// TODO Auto-generated method stub
		return false;
	}

	
	//NASE METODE
	public void addChildren(Node child) {
		children.addNode(child);
		child.setParent(this);
		
	}

	public void addColumn(Column c) {
		columns.addColumn(c);
	}
	/**
	 * Metoda lokalizuje ime i kolone cvora i imena i kolone svih njegovih potomaka
	 */
	public void localizeNodeAndChildrenNodes(ResourceBundle resourceBundle){
		
		if(resourceBundle.containsKey(localNameKey))
			name = resourceBundle.getString(localNameKey);

		
		for (int i = 0 ; i< children.getChildCount(); i++){
			((Node) children.getChildren(i)).localizeNodeAndChildrenNodes(resourceBundle);
		}
		
	}
	
	
}
